/** Short dialogue labels embedded in authored multi-party cue text. */
export const DIALOGUE_SPEAKER_ALIASES: Readonly<Record<string, string>> = {
  Channel: 'Recorded channel',
  Clerk: 'Clerk',
  Crown: 'Crown counsel Asha Renn',
  Dax: 'Defence counsel Corin Dax',
  Defence: 'Defence counsel Corin Dax',
  Dorn: 'Peli Dorn',
  Foreperson: 'Foreperson Edda Rook',
  Iven: 'Sola Iven',
  Judge: 'Judge Sel Aven',
  Merrow: 'Yara Merrow',
  Mir: 'Tovan Mir',
  Narrator: 'Narrator',
  Noor: 'Kessa Noor',
  Orr: 'Nella Orr',
  Pell: 'Jaro Pell',
  Quill: 'Sera Quill',
  Renn: 'Crown counsel Asha Renn',
  Rook: 'Foreperson Edda Rook',
  Rusk: 'Tali Rusk',
  Saye: 'Ilan Saye',
  Tey: 'Bram Tey',
  Venn: 'Mara Venn',
  Vale: 'Oren Vale',
  Vos: 'Dr Eren Vos',
}
