import type { CourtSession, LegalPhase, Scene, SceneCue } from '../model/schema'
import { commissionedVisual } from './sceneArt'

type CueInput = Omit<SceneCue, 'evidenceIds' | 'replayable'> & { evidenceIds?: string[]; replayable?: boolean }

function cue(input: CueInput): SceneCue {
  return { evidenceIds: [], replayable: false, ...input }
}

function scene(
  id: string,
  title: string,
  phase: LegalPhase,
  fallbackId: string,
  cues: SceneCue[],
  minimumSeconds: number,
  prompt: string,
  kind: NonNullable<Scene['interaction']>['kind'] = 'observe',
  options?: string[],
): Scene {
  return {
    id, title, phase,
    visual: commissionedVisual(id, {
      fallbackId,
      alt: `Illustrated courtroom view for ${title}. No legal information depends on this image.`,
      focalPoint: { x: 50, y: 44 }, captionPosition: 'bottom',
    }),
    cues, transitionSeconds: 8,
    interaction: { kind, prompt, minimumSeconds, ...(options ? { options } : {}) },
  }
}

const monday: CourtSession = {
  id: 'cw-0001-monday', ordinal: 1, day: 'Monday', title: 'The duty',
  unlockAt: '2026-08-10T08:30:00+10:00', targetMinutes: 20, prerequisiteSessionIds: [],
  scenes: [
    scene('mon-arrival', 'Take your seat', 'arrival', 'courtroom-jury-view', [
      cue({ id: 'mon-arrival-1', event: 'arrival', speaker: 'Court officer', tone: 'formal', text: 'Members of the jury panel, switch off every device except the one running this simulation. Do not search the names, science or procedures you hear. This case is wholly fictional, but your obligation is the real obligation of a juror: decide only from evidence admitted in court and the law the judge gives you.', accessibleProposition: 'Jurors must use only admitted evidence and the judge’s law; the case is fictional.' }),
      cue({ id: 'mon-arrival-2', event: 'empanelment', speaker: 'Judge Sel Aven', tone: 'formal', text: 'You have been selected after each side had the opportunity to raise lawful challenges. Nothing in that process suggests a view about the evidence. If you recognise only a similarity to some other event, put it aside. The people, service, storm and harbour in this trial exist only in the State of Orinth.', accessibleProposition: 'The jury is selected impartially and must disregard supposed parallels outside the fictional case.' }),
      cue({ id: 'mon-plea', event: 'plea', speaker: 'Clerk', tone: 'formal', text: 'Mara Venn, you are charged that, while owing an emergency-dispatch duty, you intentionally withheld rescue action and thereby murdered Ilan Saye. How do you plead? The accused answers: Not Guilty. That plea denies every element the Crown must prove.', accessibleProposition: 'Mara Venn pleads Not Guilty to murder by intentional omission.' }),
    ], 118, 'Settle into the jury viewpoint and identify the allegation—not an answer.'),
    scene('mon-oath', 'Your promise', 'arrival', 'courtroom-judge', [
      cue({ id: 'mon-oath', event: 'oath', speaker: 'Clerk', tone: 'formal', text: 'Choose an oath or affirmation. In either form you promise to try the accused faithfully and give a true verdict according to the evidence. The promise has the same force. You are not joining the Crown, the defence or the investigation. You are becoming one of twelve independent judges of fact.', accessibleProposition: 'The oath and affirmation are equally binding promises to decide according to evidence.' }),
      cue({ id: 'mon-prelim-1', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Mara Venn is presumed innocent. She need prove nothing. The Crown bears the burden throughout and must exclude every reasonable possibility consistent with innocence before you may convict. Suspicion, even grave suspicion, is not proof beyond reasonable doubt. Nor does the seriousness of a death reduce the standard.', accessibleProposition: 'The Crown alone bears the burden beyond reasonable doubt; seriousness and suspicion do not lower it.' }),
      cue({ id: 'mon-prelim-2', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Keep private notes if they help, but notes are aids rather than evidence. Do not decide witness by manner alone. Consider opportunity to observe, consistency, independent support, possible error and whether the account changed under fair testing. Do not discuss the case before retirement, even with another juror.', accessibleProposition: 'Jurors may take private notes and must assess reliability rather than demeanour alone.' }),
    ], 125, 'Choose oath or affirmation privately, then review the burden once.', 'choose-focus', ['Oath', 'Affirmation']),
    scene('mon-crown-opening', 'The Crown’s allegation', 'crown-case', 'courtroom-crown', [
      cue({ id: 'mon-crown-opening-1', event: 'crown-opening', speaker: 'Crown counsel Asha Renn', tone: 'chief', text: 'At 21:16 the accused heard a distress call from beacon AR-71. She repeated that beacon correctly, accepted the incident and had the nearest rescue craft available. Yet she lowered the priority, confirmed that deliberate change and wrote “hold—readiness.” Eleven minutes passed before Kestrel launched. Ilan Saye died before it arrived.', accessibleProposition: 'The Crown alleges a recognised distress alert was deliberately downgraded and rescue withheld for eleven minutes.' }),
      cue({ id: 'mon-crown-opening-2', event: 'crown-opening', speaker: 'Crown counsel Asha Renn', tone: 'chief', text: 'The Crown says the hold was not a mistake. Saye was a safety auditor preparing a memorandum that could suspend Venn’s certification. You will hear the recording, see the authenticated console actions and learn why eleven minutes mattered medically. The Crown must still prove knowledge, causation and murderous intent; an ugly consequence alone will not do.', accessibleProposition: 'The Crown relies on motive, console actions and survival evidence but accepts every murder element must be proved.' }),
      cue({ id: 'mon-def-reserve', event: 'defence-opening-reserved', speaker: 'Defence counsel Corin Dax', tone: 'neutral', text: 'The defence reserves its opening until the Crown has called all its evidence. That is a procedural choice, not evidence and not a sign of weakness. We ask you to hold the Crown to what its witnesses actually establish, rather than fill the silent spaces in its opening.', accessibleProposition: 'The defence lawfully reserves its opening; jurors must draw no inference from that choice.' }),
    ], 100, 'Privately note which proposition is an allegation and which already rests on an agreed fact.', 'choose-focus', ['Recognition', 'Motive', 'Causation', 'Intent']),
    scene('mon-orr-chief', 'The dispatch room', 'crown-case', 'courtroom-witness', [
      cue({ id: 'mon-orr-chief-1', event: 'witness-chief', speaker: 'Nella Orr', tone: 'chief', text: 'I supervise the duty controllers. When a controller accepts a credible distress alert, section 41 requires reasonable dispatch steps unless a greater imminent peril is reasonably prioritised. At 21:16 Venn was the controller. Dorn was the junior dispatcher. Kestrel at North Station was the nearest rescue craft to AR-71.', accessibleProposition: 'Supervisor Orr identifies Venn’s duty and Kestrel as the nearest craft.', evidenceIds: ['ex-route'] }),
      cue({ id: 'mon-orr-chief-2', event: 'exhibit-admitted', speaker: 'Nella Orr', tone: 'chief', text: 'This route diagram accurately marks the stations, beacon and ordinary path. It does not show that night’s visibility, waves or survival conditions. North Station is eleven nautical miles from AR-71. A different rescue was already assigned to the people-in-water incident shown east of the harbour.', accessibleProposition: 'The route diagram shows distance and assignments, not sea conditions or survival time.', evidenceIds: ['ex-route'], replayable: true }),
    ], 125, 'Inspect the admitted route diagram and its stated limitation.', 'inspect-exhibit'),
    scene('mon-orr-cross', 'Duty under pressure', 'crown-case', 'courtroom-defence-cross', [
      cue({ id: 'mon-orr-cross-1', event: 'witness-cross', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Section 41 does not command instant launch on every call, does it? Orr: No. A controller may reasonably prioritise a greater imminent peril and must consider craft safety. Dax: During a severe storm, choosing among incomplete reports is part of the job? Orr: Yes, but the choice still must be reasonable.', accessibleProposition: 'The dispatch duty allows reasonable prioritisation and craft-safety assessment.' }),
      cue({ id: 'mon-orr-cross-2', event: 'witness-cross', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: READY is not the same as perfect condition? Orr: Correct. It means crewed and launch-capable under the status protocol. Separate warnings may require attention. Dax: And you were not beside Venn when she made the decision? Orr: I was in another room. I cannot say what she believed.', accessibleProposition: 'READY permits launch but does not exclude warnings; Orr cannot testify to Venn’s belief.' }),
    ], 120, 'Separate the legal duty from hindsight about the eventual death.', 'choose-focus', ['Duty existed', 'Reasonable prioritisation exception', 'Witness cannot know belief']),
    scene('mon-elements', 'The questions you will eventually answer', 'crown-case', 'courtroom-judge', [
      cue({ id: 'mon-elements-1', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Do not decide the case tonight. Organise what you hear around questions. Did Venn accept a credible alert? Did she intentionally withhold a reasonable dispatch step without reasonably prioritising a greater peril? Did that omission cause death? For murder only: did she then intend death or really serious injury?', accessibleProposition: 'The murder questions concern duty breach, causation and intent; they must be considered separately.' }),
      cue({ id: 'mon-elements-2', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'An intentional act is not automatically a murderous intent. Pressing a button deliberately may prove the action was conscious; it does not by itself prove what consequence was intended. Equally, intention may be inferred from circumstances, but only if the inference is the sole reasonable conclusion from the evidence as a whole.', accessibleProposition: 'A deliberate console action is distinct from intent to cause death or serious injury.' }),
    ], 128, 'Place the day’s admitted material under the question it could lawfully help answer.', 'choose-focus', ['Duty', 'Causation', 'Murderous intent']),
    scene('mon-adjourn', 'Court rises', 'crown-case', 'courtroom-empty', [
      cue({ id: 'mon-adjourn-1', event: 'adjournment', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'The Crown’s opening is not evidence. Orr’s evidence and the route diagram are evidence, subject to the limits you heard. Between sittings, do not research emergency law, weather, rescue craft, hypothermia or any supposed real analogue. Do not let another person inspect your juror notes.', accessibleProposition: 'Only Orr’s testimony and the admitted diagram are evidence today; research and discussion remain forbidden.' }),
      cue({ id: 'mon-adjourn-2', event: 'adjournment', speaker: 'Court officer', tone: 'formal', text: 'Your progress is saved on this device. The court will resume with the junior dispatcher and the authenticated distress recording. Until then, no conclusion is required of you. The discipline of postponing judgment is part of the task.', accessibleProposition: 'The jury should keep an open mind until the evidence is complete.' }),
    ], 130, 'Close your notes without choosing a verdict.'),
  ],
}

const tuesday: CourtSession = {
  id: 'cw-0001-tuesday', ordinal: 2, day: 'Tuesday', title: 'The call',
  unlockAt: '2026-08-11T08:30:00+10:00', targetMinutes: 20, prerequisiteSessionIds: ['cw-0001-monday'],
  scenes: [
    scene('tue-resume', 'Court resumes', 'crown-case', 'courtroom-jury-view', [
      cue({ id: 'tue-resume-1', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Yesterday you heard the allegation, the dispatch duty and limited route evidence. Recall evidence as best you can, but do not invent exact words. Today a recording will be played. It may be replayed later because it is itself an admitted exhibit, but repetition does not give it extra legal weight.', accessibleProposition: 'An admitted recording may be replayed but repetition must not inflate its weight.' }),
      cue({ id: 'tue-resume-2', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'You will also hear evidence about simultaneous incidents. A busy room can explain an error, yet busyness is not a universal excuse. Ask what information reached this controller, what action she took and what reasonable alternatives then existed.', accessibleProposition: 'Workload is relevant but must be connected to Venn’s information and available choices.' }),
    ], 90, 'Re-open the duty and intent questions without reviewing a transcript.'),
    scene('tue-dorn-chief', 'The junior dispatcher', 'crown-case', 'courtroom-witness', [
      cue({ id: 'tue-dorn-chief-1', event: 'witness-chief', speaker: 'Peli Dorn', tone: 'chief', text: 'I took the first words of the call. The channel crackled, but I heard “survey vessel Lumen, beacon AR-71, taking water.” I transferred it to Venn. She leaned toward the speaker. When the caller repeated the beacon, Venn said, “AR-71, I have your position.” I entered flooding as the incident type.', accessibleProposition: 'Dorn heard AR-71 and heard Venn repeat that she had the position.', evidenceIds: ['ex-distress'] }),
      cue({ id: 'tue-dorn-chief-2', event: 'witness-chief', speaker: 'Peli Dorn', tone: 'chief', text: 'Kestrel showed READY. Venn told me, “Hold Kestrel. Keep this at priority three.” I asked whether she meant the east rescue, because that involved people already in the water. She said, “No. Seventy-one waits.” Her voice was flat. I cannot tell you from tone alone what she intended.', accessibleProposition: 'Dorn says Venn expressly held Kestrel for AR-71 but cannot infer intent from tone.', evidenceIds: ['ex-ready-display'] }),
    ], 85, 'Assess Dorn’s opportunity to hear and the limit she places on her own evidence.', 'choose-focus', ['Words heard', 'Console view', 'Tone is not intent']),
    scene('tue-recording', 'Exhibit: distress channel', 'crown-case', 'evidence-audio', [
      cue({ id: 'tue-recording-foundation', event: 'exhibit-admitted', speaker: 'Crown counsel Asha Renn', tone: 'chief', text: 'By agreement, the following is the unedited archive copy. Dorn recognises the voices and sequence; the custodian will address the hash and clock. The recording is admitted provisionally subject to that evidence. Listen for what is actually audible, including uncertainty, rather than what either advocate says you should hear.', accessibleProposition: 'The unedited recording is admitted subject to the custodian’s integrity evidence.', evidenceIds: ['ex-distress'], replayable: true }),
      cue({ id: 'tue-recording-play', event: 'exhibit-admitted', speaker: 'Recorded channel', tone: 'neutral', text: 'Saye: “Lumen to Reach control. Flooding fast. Beacon Alpha-Romeo seven-one.” Dorn: “Stand by for duty.” Venn: “Lumen, confirm seven-one.” Saye: “Seven-one. Pumps lost. Two aboard—” Static masks several seconds. Venn: “AR-71, I have your position. Maintain beacon.” Saye: “Water at the batteries.” The channel then breaks.', accessibleProposition: 'The audible recording includes AR-71, Venn’s confirmation and Saye reporting flooding and water at the batteries.', evidenceIds: ['ex-distress'], replayable: true }),
    ], 120, 'Listen once, then inspect the captioned exhibit and mark any genuinely uncertain words.', 'inspect-exhibit'),
    scene('tue-dorn-cross', 'What the room sounded like', 'crown-case', 'courtroom-defence-cross', [
      cue({ id: 'tue-dorn-cross-1', event: 'witness-cross', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: You were handling four open incidents? Dorn: Four were displayed. Dax: Alarms overlapped and the roof link failed twice? Dorn: Yes. Dax: You initially wondered whether Venn meant the east rescue? Dorn: For a moment. Dax: So a trained dispatcher beside her could be uncertain about the instruction? Dorn: About which incident, briefly—not about the words “seventy-one waits.”', accessibleProposition: 'Dorn briefly misunderstood which incident Venn meant, but maintains the express words concerned AR-71.', evidenceIds: ['ex-competing'] }),
      cue({ id: 'tue-def-objection', event: 'objection', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: What did another dispatcher tell you Venn had said earlier? Crown: Objection—hearsay. Dax: It goes to the noise in the room. Judge: Sustained before the witness answers. Ask about sounds she personally perceived, not an absent person’s account.', accessibleProposition: 'A pre-answer hearsay objection is sustained; no answer or evidence results.' }),
      cue({ id: 'tue-def-ruling', event: 'ruling', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Members of the jury, the unanswered question proves nothing. It must not prompt speculation about what an absent person might have said. Dorn may describe the room she perceived herself.', accessibleProposition: 'The unanswered hearsay question supplies no information and cannot be used.' }),
      cue({ id: 'tue-dorn-cross-2', event: 'witness-cross', speaker: 'Peli Dorn', tone: 'cross', text: 'The room was loud: alert tones, radio traffic and rain against the glazing. I could still hear Venn at the next console. She looked twice between AR-71 and Kestrel’s status. I did not see the maintenance-warning detail page open. I cannot say whether she had opened it earlier.', accessibleProposition: 'The room was noisy; Dorn did not see the warning-detail page and cannot say what Venn previously viewed.' }),
    ], 75, 'Keep the sustained question legally empty; compare only Dorn’s admitted observations.'),
    scene('tue-dorn-re', 'A confined clarification', 'crown-case', 'courtroom-crown', [
      cue({ id: 'tue-dorn-re-1', event: 'witness-reexamination', speaker: 'Crown counsel Asha Renn', tone: 'chief', text: 'Renn: Cross-examination mentioned the people-in-water incident. At the time Venn said “seventy-one waits,” had a rescue craft been assigned there? Dorn: Yes. Skimmer Two was already moving east. Renn: Did AR-71 then have any craft assigned? Dorn: No. Judge: That clarification is admitted only because cross-examination raised the competing rescue.', accessibleProposition: 'Re-examination clarifies that another craft served the east rescue while AR-71 had none.', evidenceIds: ['ex-competing'] }),
      cue({ id: 'tue-re-direction', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Re-examination is not a second opening. It may clarify a matter arising from cross-examination and may not introduce an unrelated case. Evaluate the answer with all of Dorn’s evidence, including noise, momentary confusion and her inability to speak to Venn’s mind.', accessibleProposition: 'The clarification is confined to the competing incident and does not erase limits in Dorn’s evidence.' }),
    ], 85, 'Update only the competing-peril question; do not treat re-examination as enhanced evidence.'),
    scene('tue-mir-chief', 'The system record', 'crown-case', 'evidence-console', [
      cue({ id: 'tue-mir-chief-1', event: 'witness-chief', speaker: 'Tovan Mir', tone: 'chief', text: 'Each controller signs in with a hardware key and personal code. Venn’s session accepted AR-71 at 21:16:08, changed priority two to priority three at 21:16:31 and confirmed the warning screen at 21:16:36. At 21:27:29 the same session released Kestrel. The archive clock was within two seconds of the station clock.', accessibleProposition: 'The authenticated audit log attributes acceptance, downgrade, confirmation and release eleven minutes later to Venn’s session.', evidenceIds: ['ex-audit-log'] }),
      cue({ id: 'tue-mir-chief-2', event: 'exhibit-admitted', speaker: 'Tovan Mir', tone: 'chief', text: 'The yellow strip printed automatically upon acceptance and was recovered from Venn’s tray. Its incident number matches the log. The printed beacon is AR-71. The handwritten words are “hold—readiness.” I can identify Venn’s ordinary handwriting from controlled records, but the paper itself cannot tell us when she wrote those words or what she meant.', accessibleProposition: 'The launch strip is authenticated to the incident and Venn’s handwriting, but not to a time or meaning.', evidenceIds: ['ex-launch-strip'], replayable: true }),
    ], 110, 'Inspect the action sequence, then separate logged facts from inferences about mind.', 'inspect-exhibit'),
    scene('tue-mir-cross', 'What logs cannot record', 'crown-case', 'courtroom-defence-cross', [
      cue({ id: 'tue-mir-cross-1', event: 'witness-cross', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: The confirmation screen used the words “Apply selected priority?” Mir: Yes. Dax: It did not say “Delay may kill”? Mir: No. Dax: A hardware-key record proves which account acted, not whether another person touched the controls? Mir: Technically yes, though I found no sign of that. Dax: And the log cannot record panic, mistake or intent? Mir: Correct.', accessibleProposition: 'The log proves authenticated actions and timing, but not state of mind or absolute physical identity.' }),
      cue({ id: 'tue-log-direction', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'The Crown may invite you to infer Venn operated her own authenticated console. The defence may identify the logical limits of that inference. Neither possibility becomes fact merely because counsel mentions it. Ask whether the evidence as a whole excludes a reasonable alternative.', accessibleProposition: 'Account attribution and physical operation remain factual inferences for the jury under the criminal standard.' }),
    ], 85, 'Identify which parts of the log are direct records and which require inference.', 'choose-focus', ['Timing', 'Account attribution', 'State of mind']),
    scene('tue-adjourn', 'The record remains incomplete', 'crown-case', 'courtroom-empty', [
      cue({ id: 'tue-adjourn-1', event: 'adjournment', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'You may replay the admitted distress recording and inspect the exhibits in your juror desk. Do not replay counsel’s descriptions as though they were evidence. Tomorrow you will hear from the rescue supervisor, a medical expert and the compliance director. In particular, causation and alleged motive remain contested.', accessibleProposition: 'The recording and admitted exhibits may be reviewed; causation and motive remain unproved issues.' }),
      cue({ id: 'tue-adjourn-2', event: 'adjournment', speaker: 'Court officer', tone: 'formal', text: 'Save observations, not a verdict. A useful note distinguishes “the system records this” from “this might mean that.” Court is adjourned.', accessibleProposition: 'Juror notes should distinguish recorded fact from inference and remain provisional.' }),
    ], 95, 'Close court with no verdict selected.'),
  ],
}

const wednesday: CourtSession = {
  id: 'cw-0001-wednesday', ordinal: 3, day: 'Wednesday', title: 'The eleven-minute window',
  unlockAt: '2026-08-12T08:30:00+10:00', targetMinutes: 20, prerequisiteSessionIds: ['cw-0001-tuesday'],
  scenes: [
    scene('wed-resume', 'The remaining Crown case', 'crown-case', 'courtroom-jury-view', [
      cue({ id: 'wed-resume-1', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Today the Crown completes its evidence. Expert opinion may help with matters outside ordinary experience, but an expert does not decide facts, credibility, intention or guilt. Test each opinion against its assumptions and concessions. A motive can make an allegation more understandable; absence of motive need not prove innocence, and possible motive never replaces proof.', accessibleProposition: 'Experts assist but do not decide the case; motive is neither an element nor a substitute for proof.' }),
      cue({ id: 'wed-resume-2', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Causation does not require mathematical certainty. The Crown must prove beyond reasonable doubt that the charged omission was a substantial and operating cause of death. If a reasonable possibility remains that the death would have occurred at the same time despite timely dispatch, the murder and manslaughter charges fail on causation.', accessibleProposition: 'The omission must be proved a substantial and operating cause; a reasonable same-outcome possibility defeats causation.' }),
    ], 90, 'Re-open the causation question and the limits of expert opinion.'),
    scene('wed-pell-chief', 'Kestrel at North Station', 'crown-case', 'courtroom-witness', [
      cue({ id: 'wed-pell-chief-1', event: 'witness-chief', speaker: 'Jaro Pell', tone: 'chief', text: 'I supervised Kestrel. READY meant the crew was aboard, engines warm and launch authorised. We saw a steering-pressure warning fluctuate, but the engineer had not grounded the craft. At 21:17 I called control: “Kestrel ready, warning monitored.” We received the order at 21:27 and cast off forty-eight seconds later.', accessibleProposition: 'Kestrel was authorised to launch while monitoring a warning and departed promptly when ordered.', evidenceIds: ['ex-ready-display', 'ex-warning'] }),
      cue({ id: 'wed-ready-admitted', event: 'exhibit-admitted', speaker: 'Jaro Pell', tone: 'chief', text: 'The status snapshot accurately shows the word READY. Its short label does not show the warning detail, which appeared on a separate page. A controller could dispatch while the warning was present, ask us for clarification or hold if she reasonably judged the risk too high. No automated rule made that judgment for her.', accessibleProposition: 'READY and the separate warning coexisted; the controller retained judgment and could seek clarification.', evidenceIds: ['ex-ready-display'], replayable: true }),
    ], 90, 'Inspect the display and its omitted warning detail together.', 'inspect-exhibit'),
    scene('wed-pell-cross', 'Launch was not risk-free', 'crown-case', 'courtroom-defence-cross', [
      cue({ id: 'wed-pell-cross-1', event: 'witness-cross', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: The warning concerned steering pressure in storm water? Pell: Yes. Dax: A serious loss could endanger five rescuers? Pell: It could, although our engineer judged launch permissible. Dax: You never spoke directly to Venn? Pell: My call went through the operations channel. Dax: So you cannot say she heard your exact words? Pell: I cannot say she personally heard them.', accessibleProposition: 'The warning carried real safety consequences, and Pell cannot prove Venn personally heard his readiness call.' }),
      cue({ id: 'wed-pell-re-1', event: 'witness-reexamination', speaker: 'Crown counsel Asha Renn', tone: 'chief', text: 'Renn: Did the warning require an eleven-minute diagnostic before launch? Pell: No. The engineer was monitoring it continuously. We needed no instruction to continue. Renn: If control wanted clarification, could it call? Pell: At any time. Our channel remained open.', accessibleProposition: 'Re-examination confines itself to the warning raised in cross: no diagnostic delay was required and clarification was available.' }),
    ], 85, 'Hold both propositions: launch carried risk, but no fixed diagnostic delay was required.'),
    scene('wed-vos', 'What eleven minutes could change', 'crown-case', 'evidence-medical', [
      cue({ id: 'wed-vos-chief-1', event: 'witness-chief', speaker: 'Dr Eren Vos', tone: 'chief', text: 'I modelled immersion, water temperature, clothing, reported injury and the rescue track. There is no clock that reveals an individual’s precise death. My opinion is that dispatch at 21:16 would probably have placed recovery inside a medically significant survival window. Dispatch at 21:27 probably placed it outside. “Probably” is deliberate; I cannot promise survival.', accessibleProposition: 'The expert says earlier dispatch probably materially improved survival, while rejecting certainty about the precise death time.', evidenceIds: ['ex-survival'] }),
      cue({ id: 'wed-vos-cross-1', event: 'witness-cross', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: Your model assumes Kestrel followed the ordinary route without a steering interruption? Vos: Yes. Dax: It assumes Saye entered the water near the last transmission? Vos: Within a range. Dax: At the pessimistic end of that range, timely dispatch may still have been too late? Vos: That remains possible, though less likely on the data I accepted.', accessibleProposition: 'The survival opinion depends on route and immersion-time assumptions; an earlier but still fatal outcome remains possible.', evidenceIds: ['ex-survival'] }),
      cue({ id: 'wed-vos-re-1', event: 'witness-reexamination', speaker: 'Crown counsel Asha Renn', tone: 'chief', text: 'Renn: Does acknowledging that possibility withdraw your opinion? Vos: No. Medicine often compares probabilities without certainty. On the accepted facts, eleven minutes materially changed the survival prospect. Whether that evidence satisfies the criminal standard and proves legal causation is for the jury, not me.', accessibleProposition: 'The expert maintains a material probability effect but leaves legal causation and the burden to the jury.' }),
    ], 110, 'Inspect the expert assumptions; note both the maintained opinion and the conceded possibility.', 'inspect-exhibit'),
    scene('wed-vale', 'The pending review', 'crown-case', 'courtroom-witness', [
      cue({ id: 'wed-vale-chief-1', event: 'witness-chief', speaker: 'Oren Vale', tone: 'chief', text: 'Saye was auditing controller certification. His draft proposed suspending Venn’s certification because of two earlier response delays. Three days before the storm, Venn asked me whether “Ilan was trying to end my career.” I replied that the review was unfinished and no decision had been made. I did not show her the draft.', accessibleProposition: 'Vale says Venn knew Saye was reviewing her and feared for her career, but she did not receive the draft.', evidenceIds: ['ex-review'] }),
      cue({ id: 'wed-def-objection', event: 'objection', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: Objection, relevance. Fear about an unfinished review proves no intention during a later emergency. Renn: It supplies a possible relationship and motive; I do not offer it as proof by itself. Judge: Overruled. The evidence may be considered only as possible motive and knowledge, with the limitations counsel identified.', accessibleProposition: 'A defence relevance objection is overruled; review evidence is limited to possible motive and knowledge.' }),
      cue({ id: 'wed-motive-ruling', event: 'ruling', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'A person may resent another and still perform a duty lawfully. Do not reason that resentment proves criminal character. First decide what Venn knew of the unfinished review. Only then ask whether that knowledge assists, alongside other evidence, in explaining a proved action.', accessibleProposition: 'Resentment is not criminal character evidence; motive matters only if knowledge and action are otherwise established.' }),
    ], 80, 'Inspect the memorandum and mark the boundary between its existence, Venn’s knowledge and any inferred motive.', 'inspect-exhibit'),
    scene('wed-strike', 'A sentence the jury cannot use', 'crown-case', 'courtroom-judge', [
      cue({ id: 'wed-vale-cross-1', event: 'witness-cross', speaker: 'Defence counsel Corin Dax', tone: 'cross', text: 'Dax: The memorandum was unfinished, never sent to Venn and might have changed after her response? Vale: Yes. Dax: You cannot say what Saye would ultimately recommend? Vale: No. Dax: Nor whether Venn believed the review would be fair? Vale: I can only repeat her question.', accessibleProposition: 'The review was unfinished and unseen; Vale cannot establish its eventual result or Venn’s belief about fairness.' }),
      cue({ id: 'wed-blurt', event: 'witness-cross', speaker: 'Oren Vale', tone: 'cross', text: 'When counsel asks whether there was any other basis for his concern, Vale begins: “People in the office said she had done this before—” Defence counsel immediately objects before the volunteered sentence is completed.', accessibleProposition: 'A witness begins an unresponsive workplace rumour; it is not evidence and conveys no usable proposition.' }),
      cue({ id: 'wed-postanswer-ruling', event: 'ruling', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Sustained. The volunteered words are struck. They are untested hearsay, not evidence of any earlier act, habit or character. You must reason as though they were never spoken. They will not appear in your exhibits, notes index, deliberation prompts or later analysis. Counsel, move to another subject.', accessibleProposition: 'The volunteered rumour is struck and must be entirely disregarded for every purpose.' }),
    ], 90, 'Acknowledge the ruling, then deliberately return to admitted evidence only.'),
    scene('wed-crown-close', 'The Crown closes its evidence', 'crown-case', 'courtroom-crown', [
      cue({ id: 'wed-record-admitted', event: 'exhibit-admitted', speaker: 'Tovan Mir', tone: 'chief', text: 'The complete concurrent-incident export uses the same verified clock. Four matters were open. Skimmer Two was assigned east before AR-71 was accepted. The other two were property alerts without reported persons at risk. The export records status, not everything any controller may have believed about urgency.', accessibleProposition: 'The board lists four incidents and existing assignments but does not itself prove Venn’s urgency assessment.', evidenceIds: ['ex-competing'], replayable: true }),
      cue({ id: 'wed-crown-close-1', event: 'crown-close', speaker: 'Crown counsel Asha Renn', tone: 'formal', text: 'Your Honour, that is the evidence for the Crown. The Crown closes its case. The jurors should understand that no later Crown witness will repair a missing foundation. The defence will now decide what evidence, if any, to call; the burden remains with the Crown.', accessibleProposition: 'The Crown formally closes; its evidentiary case is complete and the burden does not move.' }),
    ], 85, 'Review which murder element remains most contested after the complete Crown case.', 'choose-focus', ['Duty breach', 'Causation', 'Intent']),
    scene('wed-adjourn', 'No verdict at half-time', 'crown-case', 'courtroom-empty', [
      cue({ id: 'wed-adjourn-1', event: 'adjournment', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Do not treat the end of the Crown case as a time for a verdict. The defence may call evidence or may require the Crown to stand on what it has proved. Neither choice changes the burden. The struck words are legally absent. If they recur in your mind, identify that intrusion and put it aside without discussing their content.', accessibleProposition: 'The Crown has closed, no verdict is due, and the struck rumour remains legally absent.' }),
      cue({ id: 'wed-adjourn-2', event: 'adjournment', speaker: 'Court officer', tone: 'formal', text: 'Tomorrow the defence will open and call two witnesses. Keep your notes provisional and private. Court is adjourned.', accessibleProposition: 'The defence case begins tomorrow; jurors must remain open-minded.' }),
    ], 95, 'Close court while preserving the presumption of innocence.'),
  ],
}

const thursday: CourtSession = {
  id: 'cw-0001-thursday', ordinal: 4, day: 'Thursday', title: 'Error or intention',
  unlockAt: '2026-08-13T08:30:00+10:00', targetMinutes: 20, prerequisiteSessionIds: ['cw-0001-wednesday'],
  scenes: [
    scene('thu-opening', 'The defence case', 'defence-case', 'courtroom-defence', [
      cue({ id: 'thu-def-opening', event: 'defence-opening', speaker: 'Defence counsel Corin Dax', tone: 'neutral', text: 'The defence case is not that the response was good. It was a grave failure. The issue is why it happened and what it caused. You will hear how alarm saturation, ambiguous status design and a genuine steering warning can produce a conscious hold without an intention to harm. A terrible decision is not automatically murder.', accessibleProposition: 'The defence admits a serious failure but disputes murderous intent and causation.' }),
      cue({ id: 'thu-silence', event: 'silence-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Mara Venn will not give evidence. She has an absolute right not to. Her silence cannot fill a gap, strengthen the Crown case, show guilt, avoid an explanation or be used in deliberation for any adverse purpose. Decide whether the Crown evidence proves its case; do not ask the accused to prove an alternative story.', accessibleProposition: 'The accused’s silence carries no adverse inference and cannot repair the Crown case.' }),
    ], 100, 'Keep the defence theory distinct from evidence and confirm that silence proves nothing.'),
    scene('thu-rusk-chief', 'Human limits in an alarm room', 'defence-case', 'courtroom-witness', [
      cue({ id: 'thu-rusk-chief-1', event: 'witness-chief', speaker: 'Tali Rusk', tone: 'chief', text: 'I study decision-making in high-alarm systems. The incident display placed priority, craft status and multiple alerts together, while warning detail sat on another page. Under overload, a person may consciously press a control yet misunderstand which risk the action manages. That describes a recognised error mechanism. It does not tell you that Venn made that error.', accessibleProposition: 'The interface could produce a conscious but mistaken action; the expert cannot say it actually did so here.' }),
      cue({ id: 'thu-rusk-chief-2', event: 'witness-chief', speaker: 'Tali Rusk', tone: 'chief', text: 'The word READY is especially vulnerable to “label capture”: attention stops at the reassuring headline or, conversely, overreacts to a remembered warning without reopening its detail. A short handwritten note such as “hold—readiness” fits either a safety check or an attempt to disguise delay. Human-factors science cannot choose between those meanings.', accessibleProposition: 'The READY label and note support competing interpretations; human-factors evidence cannot select Venn’s actual intent.', evidenceIds: ['ex-ready-display', 'ex-launch-strip'] }),
    ], 95, 'Compare the error mechanism to the actual system design without assuming it occurred.', 'inspect-exhibit'),
    scene('thu-rusk-cross', 'An explanation is not an acquittal', 'defence-case', 'courtroom-crown-cross', [
      cue({ id: 'thu-rusk-cross-1', event: 'witness-cross', speaker: 'Crown counsel Asha Renn', tone: 'cross', text: 'Renn: Your mechanism does not explain why Venn repeated AR-71, then said “seventy-one waits”? Rusk: It can explain competing-risk classification, not failure to hear the number. Renn: Nor why she confirmed a downgrade? Rusk: A conscious confirmation can still implement an erroneous judgment. Renn: You offer a possibility, not a diagnosis? Rusk: Correct.', accessibleProposition: 'Rusk offers a possible error mechanism but cannot diagnose Venn or explain away recognition of AR-71.' }),
      cue({ id: 'thu-crown-objection', event: 'objection', speaker: 'Crown counsel Asha Renn', tone: 'cross', text: 'Defence: So the Crown’s theory ignores everything known about human cognition? Crown: Objection—argumentative. Judge: Sustained before the witness answers. Re-examination may clarify the expert’s limits, not ask her to endorse counsel’s criticism of the opposing case.', accessibleProposition: 'A Crown argumentative objection is sustained before answer; no endorsement results.' }),
      cue({ id: 'thu-rusk-re-1', event: 'witness-reexamination', speaker: 'Defence counsel Corin Dax', tone: 'chief', text: 'Dax: Is describing a recognised mechanism the same as saying it occurred? Rusk: No. It helps a jury evaluate whether error remains reasonably possible given the actual conditions. It is not an opinion on intention, credibility or verdict.', accessibleProposition: 'Re-examination confines Rusk’s evidence to assessing a reasonable error possibility, not intent or verdict.' }),
    ], 85, 'Retain both limits: possibility may matter to reasonable doubt, but it is not a diagnosis.'),
    scene('thu-quill-chief', 'The warning beneath READY', 'defence-case', 'evidence-maintenance', [
      cue({ id: 'thu-quill-chief-1', event: 'witness-chief', speaker: 'Sera Quill', tone: 'chief', text: 'Before shift I recorded intermittent steering-pressure fluctuation. It did not ground Kestrel, but in those seas a worsening fault could make return dangerous. The controller’s status feed showed READY on its main tile and an amber symbol leading to my detail. I did not know whether Venn opened that detail. Controllers had authority to seek advice or dispatch.', accessibleProposition: 'A real but non-grounding warning was available behind the READY tile; Quill cannot prove Venn viewed it.', evidenceIds: ['ex-warning', 'ex-ready-display'] }),
      cue({ id: 'thu-warning-admitted', event: 'exhibit-admitted', speaker: 'Sera Quill', tone: 'chief', text: 'This is my contemporaneous entry. “Monitor on launch; abort for sustained pressure loss.” Monitor on launch means launch was permitted. It also means the risk was not imaginary. The maintenance record cannot establish whether a hold of one minute, eleven minutes or no time was reasonable without knowing what the controller understood.', accessibleProposition: 'The warning permitted monitored launch and was genuine, but does not prescribe or justify an eleven-minute hold.', evidenceIds: ['ex-warning'], replayable: true }),
    ], 105, 'Inspect the exact warning language rather than reducing it to safe or unsafe.', 'inspect-exhibit'),
    scene('thu-quill-cross', 'Available choices', 'defence-case', 'courtroom-crown-cross', [
      cue({ id: 'thu-quill-cross-1', event: 'witness-cross', speaker: 'Crown counsel Asha Renn', tone: 'cross', text: 'Renn: No one ordered Kestrel grounded? Quill: No. Renn: No diagnostic required eleven minutes? Quill: No. Renn: Control could call you or Pell? Quill: Yes. Renn: The launch then occurred with the same warning still present? Quill: Yes, monitored throughout.', accessibleProposition: 'The warning never grounded Kestrel, required no eleven-minute diagnostic and remained unchanged at launch.' }),
      cue({ id: 'thu-quill-re-1', event: 'witness-reexamination', speaker: 'Defence counsel Corin Dax', tone: 'chief', text: 'Dax: Who had legal authority to balance rescuer safety and distress priority? Quill: The duty controller, informed by operations. Dax: Did READY erase the warning? Quill: No. Judge: That is confined to the authority and warning matters raised in cross; it is not an opinion that Venn exercised the authority reasonably.', accessibleProposition: 'The controller held dispatch authority and the warning remained relevant, but Quill does not say Venn acted reasonably.' }),
    ], 90, 'Distinguish the existence of discretion from whether it was exercised honestly or reasonably.'),
    scene('thu-defence-record', 'The defence rests on the whole record', 'defence-case', 'courtroom-judge', [
      cue({ id: 'thu-defence-theory', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'The defence has called its witnesses and indicates that it will tender no statement from the accused. That is procedural information, not evidence and not a final address. The system-design and warning evidence remains subject to the limits you heard. Do not yet decide whether it supports error, safety assessment or any conclusion about intention.', accessibleProposition: 'The defence calls no accused statement; the jury must not treat that procedural choice as evidence or decide the competing inferences yet.' }),
      cue({ id: 'thu-silence-repeat', event: 'silence-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Counsel’s formulation is an argument about possibilities in admitted evidence; it is not testimony from Venn. Do not accept it merely because no one cross-examined her, and do not reject it merely because she did not testify. Ask only whether the Crown excluded reasonable possibilities consistent with innocence of each offence.', accessibleProposition: 'The defence theory is argument, and the accused’s silence neither supports nor undermines it.' }),
    ], 90, 'Test the defence possibility against admitted evidence without demanding an explanation from Venn.'),
    scene('thu-def-close', 'Evidence closes', 'defence-case', 'courtroom-judge', [
      cue({ id: 'thu-def-close-1', event: 'defence-close', speaker: 'Defence counsel Corin Dax', tone: 'formal', text: 'Your Honour, the defence calls no further evidence and closes its case.', accessibleProposition: 'The defence formally closes; all evidence in the trial is now complete.' }),
      cue({ id: 'thu-close-direction', event: 'preliminary-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'All evidence is complete. Nothing counsel says tomorrow becomes evidence. The Crown has no reply evidence and will not be permitted to split its case around the defence. Tomorrow each side addresses you, then I will give the governing law and a structured path through the possible verdicts.', accessibleProposition: 'Evidence is complete; closings are argument, and final directions will follow both.' }),
    ], 85, 'Mark the evidentiary record closed; do not search for material outside it.'),
    scene('thu-adjourn', 'Before the addresses', 'defence-case', 'courtroom-empty', [
      cue({ id: 'thu-adjourn-1', event: 'adjournment', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Continue to withhold verdict. You may organise admitted evidence under duty, causation and intent. You may also note source limits. Do not count witnesses or exhibits as votes. One reliable item can outweigh many weak ones, and a number of individually uncertain circumstances do not become certain merely by accumulation.', accessibleProposition: 'Evidence must be weighed for quality and combined reasoning, not counted.' }),
      cue({ id: 'thu-adjourn-2', event: 'adjournment', speaker: 'Court officer', tone: 'formal', text: 'The court will sit tomorrow for addresses and the final summing-up. Your private juror desk contains admitted material only. Court is adjourned.', accessibleProposition: 'Only admitted material remains available for Friday’s consideration.' }),
    ], 95, 'Close your notes with the verdict still unsealed.'),
  ],
}

const friday: CourtSession = {
  id: 'cw-0001-friday', ordinal: 5, day: 'Friday', title: 'The questions of law',
  unlockAt: '2026-08-14T08:30:00+10:00', targetMinutes: 20, prerequisiteSessionIds: ['cw-0001-thursday'],
  scenes: [
    scene('fri-legal-submissions', 'Before the jury returns', 'addresses', 'courtroom-empty', [
      cue({ id: 'fri-submissions-1', event: 'adjournment', speaker: 'Narrator', tone: 'neutral', text: 'Before jurors enter, counsel settle the lawful questions with the judge. The Crown accepts that manslaughter must be left as a genuine alternative, not a bargaining position. The defence obtains a direction that Venn’s silence cannot be used and that the maintenance warning may be considered on both intent and reasonable prioritisation.', accessibleProposition: 'Outside the jury’s presence, the court settles murder, manslaughter, silence and warning directions.' }),
      cue({ id: 'fri-submissions-2', event: 'adjournment', speaker: 'Narrator', tone: 'neutral', text: 'The judge rejects a proposed direction equating the priority confirmation with murderous intent. A conscious button press can prove a deliberate action, but intent about death remains a separate inference. The jury returns after these rulings; it receives only the law as finally settled.', accessibleProposition: 'The court refuses to equate a deliberate console action automatically with murderous intent.' }),
    ], 80, 'Observe how legal submissions narrow the questions without adding evidence.'),
    scene('fri-crown-close', 'Crown address', 'addresses', 'courtroom-crown', [
      cue({ id: 'fri-crown-closing-1', event: 'crown-closing', speaker: 'Crown counsel Asha Renn', tone: 'formal', text: 'The Crown asks you to reason from the joined circumstances, not one dramatic phrase. Venn heard and repeated AR-71. Her authenticated session accepted, downgraded and confirmed it. She singled it out—“seventy-one waits”—while another craft handled the greater visible peril. Kestrel was READY, no diagnostic was required, and no clarification call was made.', accessibleProposition: 'The Crown combines recognition, deliberate actions, existing assignments and available launch or clarification.' }),
      cue({ id: 'fri-crown-closing-2', event: 'crown-closing', speaker: 'Crown counsel Asha Renn', tone: 'formal', text: 'Why hold this incident? The unfinished review supplied a reason, though motive alone proves nothing. Why eleven minutes? The note and actions, the Crown submits, show a delay allowed to run until the survival chance closed. Vos could not promise life; criminal causation does not demand a promise. The Crown says the reasonable inference is an intentional withholding meant to cause at least really serious injury.', accessibleProposition: 'The Crown argues motive and duration support murderous intent and that probabilistic medical evidence proves causation.' }),
    ], 90, 'Map each Crown inference to admitted evidence and identify where an alternative must be excluded.', 'reasoning', ['connect', 'test-source', 'challenge-inference', 'apply-burden']),
    scene('fri-defence-close', 'Defence address', 'addresses', 'courtroom-defence', [
      cue({ id: 'fri-defence-closing-1', event: 'defence-closing', speaker: 'Defence counsel Corin Dax', tone: 'formal', text: 'Do not let the death rewrite the decision as it appeared at 21:16. The room was saturated, READY concealed a genuine warning, and even Dorn first wondered which rescue the hold concerned. Rusk identified a recognised error mechanism without pretending to read Venn’s mind. Quill confirmed the safety risk was real. A bad judgment may be deliberate in action yet innocent of murderous purpose.', accessibleProposition: 'The defence relies on overload, display ambiguity and a genuine warning to preserve reasonable doubt about intent.' }),
      cue({ id: 'fri-defence-closing-2', event: 'defence-closing', speaker: 'Defence counsel Corin Dax', tone: 'formal', text: 'Causation also remains uncertain. Vos assumed route, immersion range and no steering interruption. At the pessimistic end, timely dispatch may still have been too late. The review was unfinished and unseen. You are not required to explain the eleven minutes. Unless the Crown excludes error, safety assessment and a same-outcome possibility beyond reasonable doubt, your verdict must not be guilty.', accessibleProposition: 'The defence argues expert assumptions and limited motive evidence leave reasonable doubt on causation and intent.' }),
    ], 90, 'Test the defence alternatives for evidentiary support without shifting the burden to the accused.', 'reasoning', ['distinguish', 'raise-alternative', 'test-source', 'apply-burden']),
    scene('fri-burden', 'The judge—not counsel—states the law', 'directions', 'courtroom-judge', [
      cue({ id: 'fri-summing-burden', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Counsel’s addresses are submissions, not evidence. Where their recollection differs from yours, your honest recollection governs. Venn remains presumed innocent. She has not testified and that fact may not be used against her in any way. The Crown must prove every required fact beyond reasonable doubt; Venn need not prove accident, error, safety concern or any other possibility.', accessibleProposition: 'Closings are argument; the Crown retains the burden and silence cannot be used.' }),
      cue({ id: 'fri-summing-circumstantial', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'The Crown relies substantially on circumstantial reasoning. You may combine circumstances, but guilt must be the only reasonable conclusion available from the proved facts. An alternative is not reasonable merely because imagination can state it; nor may you reject an evidence-based alternative because it is inconvenient or not proved by the defence.', accessibleProposition: 'Circumstantial guilt must be the only reasonable conclusion; supported alternatives need not be proved by the defence.' }),
    ], 85, 'Set counsel’s rhetoric aside and reopen the element trail.'),
    scene('fri-murder-trail', 'First question: murder', 'directions', 'courtroom-judge', [
      cue({ id: 'fri-summing-duty', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Consider murder first. One: did section 41 impose the accepted-alert duty? That is agreed. Two: did Venn intentionally fail to take a reasonable dispatch step, without reasonably prioritising a greater imminent peril? A conscious hold is not enough if the Crown leaves a reasonable possibility that it was reasonable safety prioritisation.', accessibleProposition: 'Murder first requires an intentional duty breach not reasonably explained by prioritising greater peril.' }),
      cue({ id: 'fri-summing-causation', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Three: did that omission substantially and operatively cause Saye’s death? Apply the criminal standard to Vos’s bounded opinion and its assumptions. The law does not require certainty, but probability language does not automatically satisfy reasonable doubt. If a reasonable same-outcome possibility remains, acquit of both homicide offences.', accessibleProposition: 'Causation must be proved beyond reasonable doubt despite probabilistic expert evidence.' }),
      cue({ id: 'fri-summing-intent', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Four, only if the first three are proved: at the time of withholding dispatch, did Venn intend death or really serious injury? You may infer intent from proved circumstances, including words, actions and any motive you find. The inference must be the only reasonable one. Recklessness, indifference, negligence or anger is not the intent required by s 18.', accessibleProposition: 'Murder additionally requires intent to cause death or really serious injury, distinct from recklessness or negligence.' }),
    ], 95, 'Work through duty, causation and murderous intent in order.', 'choose-focus', ['Duty breach', 'Causation', 'Intent to kill or seriously injure']),
    scene('fri-manslaughter-trail', 'Only if murder is not proved', 'directions', 'courtroom-judge', [
      cue({ id: 'fri-summing-manslaughter', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'If, and only if, murder is not proved, consider manslaughter under s 22. Ask whether Venn deliberately omitted a dispatch step required by her duty, whether that omission caused death, and whether her departure from reasonable care was so great, with so high a risk of death or serious injury, that it merits criminal punishment. This offence does not require an intention to harm.', accessibleProposition: 'Manslaughter is considered only after murder fails and requires criminally grave negligence, causation and duty breach, not intent to harm.' }),
      cue({ id: 'fri-summing-no-compromise', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Manslaughter is not a compromise between jurors who favour murder and jurors who favour acquittal. It is a separate offence with separate elements. Return it only if every juror joining that verdict is satisfied of those elements beyond reasonable doubt. If causation or criminal negligence is not proved, the lawful verdict is Not Guilty.', accessibleProposition: 'Manslaughter cannot be a compromise; its own elements must be proved or the verdict is Not Guilty.' }),
    ], 95, 'Keep manslaughter separate from both murder and ordinary error.', 'choose-focus', ['Criminally grave duty breach', 'Causation', 'No compromise']),
    scene('fri-evidence-limits', 'How to use the record', 'directions', 'evidence-desk', [
      cue({ id: 'fri-summing-expert', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Vos and Rusk are experts in different fields. Consider qualifications, reasoning, assumptions, concessions and consistency with proved facts. Neither may decide legal causation, Venn’s intention or your verdict. The distress recording may be replayed, but do not give it greater weight merely because a recording feels vivid or can be repeated.', accessibleProposition: 'Experts and replayable evidence remain subject to limits and do not decide legal questions.' }),
      cue({ id: 'fri-summing-motive', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'The review memorandum is available only on possible knowledge and motive. It was unfinished and unseen. It is not proof of bad character. The volunteered workplace words were struck and are legally absent; they cannot support propensity, motive, credibility or any other inference and are not available in your juror desk.', accessibleProposition: 'The review has limited motive use; the struck rumour has no lawful use and is unavailable.' }),
      cue({ id: 'fri-summing-exhibits', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Read each exhibit with its limitation: the diagram omits conditions; READY omits warning detail; the warning permits launch but records risk; the log shows authenticated actions, not mind; the handwritten note has no time; the incident board records status, not belief. Accuracy about a narrow fact does not prove a larger proposition.', accessibleProposition: 'Each admitted exhibit has a specific use and limitation that travels with it into deliberation.' }),
    ], 100, 'Open each admitted exhibit’s limitation before relying on it.', 'inspect-exhibit'),
    scene('fri-retire', 'Retirement', 'directions', 'courtroom-jury-box', [
      cue({ id: 'fri-retire-direction', event: 'summing-up', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'Your verdict should be unanimous if honest discussion can achieve it. Each juror must decide personally after listening fairly to the others. Do not surrender an honestly held view merely to finish, and do not refuse to reconsider it. Do not discuss punishment. If you need legal help, send a written note through the court officer without revealing ballot numbers.', accessibleProposition: 'Jurors should seek unanimity without surrendering honest judgment, avoid punishment, and use written notes for legal help.' }),
      cue({ id: 'fri-retire', event: 'retire', speaker: 'Court officer', tone: 'formal', text: 'All rise. Members of the jury, take the admitted exhibits and question trail to the jury room. The accused remains before the court. Your deliberation is now private.', accessibleProposition: 'The jury formally retires with admitted exhibits and the legal question trail.' }),
      cue({ id: 'fri-adjourn', event: 'adjournment', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'We begin tomorrow. Tonight, do not rehearse arguments with anyone or seek outside material. Arrive prepared to identify one concern, not to announce a camp. Our first task is to understand the questions together.', accessibleProposition: 'Deliberation begins tomorrow with issues rather than public allegiances.' }),
    ], 80, 'Retire without taking or revealing a ballot.'),
  ],
}

const saturday: CourtSession = {
  id: 'cw-0001-saturday', ordinal: 6, day: 'Saturday', title: 'First positions',
  unlockAt: '2026-08-15T08:30:00+10:00', targetMinutes: 20, prerequisiteSessionIds: ['cw-0001-friday'],
  scenes: [
    scene('sat-room', 'The door closes', 'deliberation', 'jury-room-wide', [
      cue({ id: 'sat-room-1', event: 'jury-discussion', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'No one needs to declare a verdict yet. Let us name the point that most needs testing. Mine is the step from a deliberate hold to an intention to cause death. We will use the judge’s question trail, one element at a time, and keep every claim tied to admitted evidence.', accessibleProposition: 'The foreperson starts with issues and evidence rather than public verdict camps.' }),
      cue({ id: 'sat-room-2', event: 'jury-discussion', speaker: 'Niko Pell', tone: 'deliberation', text: 'My concern is causation. Vos said “probably” and also admitted a same-outcome possibility. That does not make the opinion worthless, but I want us to articulate why the remaining possibility is or is not reasonable on all the facts.', accessibleProposition: 'A juror identifies the need to assess whether the expert’s conceded same-outcome possibility is reasonable.' }),
      cue({ id: 'sat-room-3', event: 'jury-discussion', speaker: 'Lina Fei', tone: 'deliberation', text: 'Mine is the warning. READY permitted launch, yet the amber detail carried a genuine rescuer risk. I want to compare the warning with what Venn actually did: hold, no recorded clarification, then launch under the same condition.', accessibleProposition: 'A juror frames the warning against the unchanged later launch and absence of recorded clarification.' }),
    ], 90, 'Choose the legal question that presently needs the most testing.', 'choose-focus', ['Duty breach', 'Causation', 'Murderous intent', 'Criminal negligence']),
    scene('sat-concerns', 'Eleven concerns, not eleven camps', 'deliberation', 'jury-room-circle', [
      cue({ id: 'sat-concerns-1', event: 'jury-discussion', speaker: 'Ari Tem', tone: 'deliberation', text: 'The audit log is exact about actions but silent about thought. I want to know whether words, sequence and motive legitimately close that gap. Sola Iven answers that the repeated beacon and explicit “waits” matter more to her than the button labels, while Mara’s uncompleted review troubles her only if knowledge is proved.', accessibleProposition: 'Jurors distinguish exact action records from the inference of intent and limit motive to proved knowledge.' }),
      cue({ id: 'sat-concerns-2', event: 'jury-discussion', speaker: 'Bram Tey', tone: 'deliberation', text: 'The system design gives me a real error mechanism, not merely a story invented by counsel. But Rusk could not say it occurred. Kessa Noor adds that a reasonable possibility must emerge from evidence while the defence still bears no burden to establish it.', accessibleProposition: 'Jurors recognise an evidence-based error possibility without shifting the burden or treating possibility as diagnosis.' }),
      cue({ id: 'sat-concerns-3', event: 'jury-discussion', speaker: 'Daro Sen', tone: 'deliberation', text: 'We should be careful not to convert eleven minutes into eleven separate proofs. Time can support an inference, but only in context. Yara Voss asks what a person intending harm would expect when the call, account and eventual release all remained permanently logged.', accessibleProposition: 'Jurors test the significance of duration and the competing inference from permanent logging.' }),
    ], 90, 'Select admitted evidence and a reasoning move; do not select a juror to pressure.', 'reasoning', ['connect', 'distinguish', 'test-source', 'challenge-inference', 'raise-alternative', 'apply-burden']),
    scene('sat-provisional', 'Seal before you see the room', 'deliberation', 'jury-room-ballot', [
      cue({ id: 'sat-provisional-direction', event: 'jury-discussion', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'We will take a private provisional ballot to discover what requires discussion. It is not a verdict, and no one’s individual selection will be published. Before the aggregate appears, each of us must make an independent choice. That prevents the visible room from substituting for personal judgment.', accessibleProposition: 'Each juror independently seals a provisional choice before aggregate totals appear.' }),
      cue({ id: 'sat-provisional-vote', event: 'provisional-vote', speaker: 'Court officer', tone: 'formal', text: 'Choose Murder, Manslaughter, Not Guilty or Unable to Agree at this stage. Murder means every s 18 element is presently proved. Manslaughter is reached only after murder fails and every s 22 element is proved. Unable to Agree is a provisional state, not avoidance. Your choice seals when submitted.', accessibleProposition: 'The player seals one lawful provisional position before seeing any aggregate.' }),
    ], 140, 'Seal your provisional position. You cannot revise it merely after seeing the count.', 'seal-vote', ['Murder', 'Manslaughter', 'Not Guilty', 'Unable to agree']),
    scene('sat-first-ballot', 'The first aggregate', 'deliberation', 'jury-room-tally', [
      cue({ id: 'sat-first-ballot', event: 'first-ballot', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'The anonymous aggregate is now displayed, including your sealed position. No seat is identified. It shows division across murder, manslaughter and acquittal, with at least one juror still unable to choose. We will not treat the largest group as presumptively right. The count tells us where disagreement exists, not how to resolve it.', accessibleProposition: 'Only an anonymous aggregate appears after the player votes; plurality has no legal authority.' }),
      cue({ id: 'sat-ballot-process', event: 'jury-discussion', speaker: 'Omri Cade', tone: 'deliberation', text: 'Let us ask a person who doubts causation to state the evidence supporting that doubt, then someone else should test it without guessing their vote. Afterward we do the same for intent and criminal negligence. No names beside positions, no demand that a minority justify its existence.', accessibleProposition: 'The room tests reasons by legal issue without exposing or coercing minority jurors.' }),
    ], 85, 'Read the aggregate only after your vote is sealed; then choose an issue, not a faction.'),
    scene('sat-causation', 'Testing the medical window', 'deliberation', 'jury-room-evidence', [
      cue({ id: 'sat-causation-1', event: 'jury-discussion', speaker: 'Niko Pell', tone: 'deliberation', text: 'Vos’s model puts earlier recovery probably inside a significant window, but its pessimistic immersion range permits the same death. My question is whether that possibility is reasonable given the last transmission, not merely conceivable. The recording places Saye conscious near 21:16, though it cannot reveal later deterioration.', accessibleProposition: 'The causation debate connects the expert’s range with the conscious last transmission while retaining uncertainty.' }),
      cue({ id: 'sat-causation-2', event: 'jury-discussion', speaker: 'Toma Reed', tone: 'deliberation', text: 'The ordinary route assumption also matters, but Kestrel launched with the warning and no steering interruption is recorded. We must not invent a breakdown. At the same time, absence of a recorded breakdown does not prove the earlier journey would have matched exactly. I presently give the model substantial, not conclusive, weight.', accessibleProposition: 'A juror rejects an invented breakdown while preserving uncertainty about a counterfactual earlier journey.' }),
      cue({ id: 'sat-causation-3', event: 'jury-discussion', speaker: 'Edda Rook', tone: 'deliberation', text: 'That is the right form of disagreement: identify the assumption, identify the admitted fact bearing on it, then apply the burden. Nobody should say the family deserves certainty or the accused should explain the timing. Neither is a lawful reason.', accessibleProposition: 'Causation reasoning must use admitted evidence and the burden, not sympathy or demands on the accused.' }),
    ], 90, 'Apply one reasoning move to the survival opinion and an admitted fact.', 'reasoning', ['connect', 'test-source', 'challenge-inference', 'apply-burden']),
    scene('sat-improper', 'Arguments the room rejects', 'deliberation', 'jury-room-circle', [
      cue({ id: 'sat-improper-1', event: 'jury-discussion', speaker: 'Bram Tey', tone: 'deliberation', text: 'Someone says that if Venn had an innocent explanation she would have testified. Kessa answers immediately: the judge forbade that reasoning. Silence supplies nothing and cannot shift the burden. The room removes the claim from its board; repeating it would reduce, not increase, the speaker’s influence.', accessibleProposition: 'The jury rejects an adverse inference from silence and applies an influence penalty to repeating it.' }),
      cue({ id: 'sat-improper-2', event: 'jury-discussion', speaker: 'Sola Iven', tone: 'deliberation', text: 'Another voice asks what sentence follows murder. Edda stops the discussion. Punishment is not our task and may distort whether elements are proved. We return to the intent inference. The same correction applies to sympathy for Saye, dislike of Venn or speculation about material the judge struck.', accessibleProposition: 'The room excludes punishment, sympathy, character and struck material from deliberation.' }),
    ], 80, 'Identify and correct an improper argument without debating its forbidden content.', 'reasoning', ['apply-burden', 'test-source']),
    scene('sat-note', 'A question for the judge', 'deliberation', 'jury-note-paper', [
      cue({ id: 'sat-jury-note', event: 'jury-note', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'The jury writes: “For murder, if we find the controller deliberately held the craft while aware that death was a possible result, is awareness of that risk enough to prove the required intent? Please restate the difference between murder and manslaughter.” No ballot numbers or juror identities appear.', accessibleProposition: 'The jury asks whether awareness of possible death equals murderous intent and requests the offence distinction.' }),
      cue({ id: 'sat-judge-response', event: 'judge-response', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'In open court: No. Awareness that death or serious injury was possible, without an intention to cause either, does not satisfy s 18. For murder the Crown must prove intention to cause death or really serious injury. If murder fails, s 22 asks separately about deliberate duty breach, causation and negligence so grave, with risk so high, that it merits criminal punishment.', accessibleProposition: 'Possible-risk awareness alone is not murderous intent; manslaughter has a distinct criminal-negligence test.' }),
    ], 105, 'Read the written question and the complete open-court answer once.', 'jury-note'),
    scene('sat-separate', 'Overnight separation', 'deliberation', 'courtroom-empty', [
      cue({ id: 'sat-separate-1', event: 'adjournment', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'The jury may separate overnight. Do not discuss the case outside the jury room, communicate a view, search any subject, or consume commentary that seems analogous. Keep an open mind. Tomorrow you may reconsider any provisional position for reasons arising from lawful discussion, not merely because of the count.', accessibleProposition: 'Jurors separate overnight without discussion or research and may later reconsider only through lawful reasoning.' }),
      cue({ id: 'sat-separate-2', event: 'adjournment', speaker: 'Court officer', tone: 'formal', text: 'The room’s anonymous aggregate and your private notes are saved locally. Individual juror positions remain sealed. Deliberation resumes tomorrow.', accessibleProposition: 'Only aggregate state and private notes persist; individual authored-juror votes remain hidden.' }),
    ], 80, 'Leave the room without changing your provisional vote merely to match others.'),
  ],
}

const sunday: CourtSession = {
  id: 'cw-0001-sunday', ordinal: 7, day: 'Sunday', title: 'The verdict',
  unlockAt: '2026-08-16T08:30:00+10:00', targetMinutes: 20, prerequisiteSessionIds: ['cw-0001-saturday'],
  scenes: [
    scene('sun-resume', 'Deliberation resumes', 'deliberation', 'jury-room-morning', [
      cue({ id: 'sun-resume-1', event: 'jury-discussion', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'We resume with the judge’s answer: possible risk is not murderous intent. That may move a person away from murder without deciding manslaughter or acquittal. We will revisit each offence in sequence. No one should announce that a changed view proves weakness; responsible reconsideration is part of deliberation.', accessibleProposition: 'The room applies the judge’s answer and treats reasoned reconsideration as legitimate.' }),
      cue({ id: 'sun-resume-2', event: 'jury-discussion', speaker: 'Yara Voss', tone: 'deliberation', text: 'The intent inference is weaker for me after separating possible consequence from intended consequence. Yet the exact beacon, express hold, confirmed downgrade and unchanged-warning launch still demand explanation—not from Venn, but from the Crown’s circumstantial case. I want to know whether those facts exclude a grave but non-murderous decision.', accessibleProposition: 'A juror weakens the murder inference while still testing whether the circumstances prove a grave lesser offence.' }),
    ], 95, 'Choose which element the judge’s answer changes, if any.', 'reasoning', ['distinguish', 'challenge-inference', 'apply-burden']),
    scene('sun-negligence', 'The alternative is not a midpoint', 'deliberation', 'jury-room-elements', [
      cue({ id: 'sun-negligence-1', event: 'jury-discussion', speaker: 'Lina Fei', tone: 'deliberation', text: 'For manslaughter, the warning cannot simply disappear. The question is whether holding without calling Pell or Quill, then launching under the same warning eleven minutes later, departed so greatly from reasonable care that it was criminal. The unchanged condition can support that inference, but we still need causation.', accessibleProposition: 'Manslaughter reasoning compares the unexplained delay and available clarification with the unchanged warning, subject to causation.' }),
      cue({ id: 'sun-negligence-2', event: 'jury-discussion', speaker: 'Ari Tem', tone: 'deliberation', text: 'We must not choose manslaughter because it feels emotionally between murder and acquittal. If the Crown has not proved causation, both offences fail. If causation is proved but murderous intent is not, we then ask whether the duty breach crossed the demanding criminal-negligence threshold.', accessibleProposition: 'Manslaughter follows a legal sequence and cannot compromise a causation doubt.' }),
    ], 100, 'Apply the manslaughter questions independently, beginning only after murder fails.', 'choose-focus', ['Deliberate duty breach', 'Causation', 'Criminally grave negligence']),
    scene('sun-second-ballot', 'A second private ballot', 'deliberation', 'jury-room-ballot', [
      cue({ id: 'sun-second-ballot', event: 'second-ballot', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'After further discussion, each juror votes privately again. The aggregate changes, but no individual path is exposed. Unanimity has not been reached. The court-clock records more than eight hours of deliberation across the two days. That fact does not weaken the standard or authorise an immediate majority verdict.', accessibleProposition: 'A second anonymous ballot remains divided after more than eight court hours; majority is not yet authorised.' }),
      cue({ id: 'sun-ballot-reflect', event: 'jury-discussion', speaker: 'Omri Cade', tone: 'deliberation', text: 'Before asking the judge for help, let us state the live disagreement precisely. Some accept medical causation and criminal negligence but not intent. Others consider the same-outcome possibility reasonable. A smaller view says the sequence excludes innocent error and proves murder. Those are legal disagreements, not stubborn personalities.', accessibleProposition: 'The remaining division concerns intent, causation and criminal negligence rather than juror character.' }),
    ], 130, 'Cast a fresh private position based on the discussion, then view only the aggregate.', 'second-vote', ['Murder', 'Manslaughter', 'Not Guilty', 'Unable to agree']),
    scene('sun-persevere', 'The court asks for one more effort', 'deliberation', 'courtroom-judge', [
      cue({ id: 'sun-perseverance', event: 'perseverance-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'I understand you have not agreed. Return and make one further honest effort. Listen to reasons you may have misunderstood and re-examine your own, but no juror must surrender an honestly held view merely to obtain a verdict. The burden and elements do not change with time. If genuine disagreement remains, you must say so.', accessibleProposition: 'The judge requests further discussion without coercion or changing the law, and preserves a hung outcome.' }),
      cue({ id: 'sun-further-discussion', event: 'jury-discussion', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'We comply by testing one proposition from the minority and one from the largest group. We do not ask anyone to defend being outnumbered. The court clock advances transparently while we recheck the recording, warning, log, expert limits and element trail.', accessibleProposition: 'Further discussion fairly tests competing reasons and does not pressure a numerical minority.' }),
    ], 90, 'Contribute one further evidence-linked reason before any majority direction.', 'reasoning', ['connect', 'distinguish', 'test-source', 'challenge-inference', 'raise-alternative', 'apply-burden']),
    scene('sun-majority', 'Majority becomes legally available', 'deliberation', 'courtroom-judge', [
      cue({ id: 'sun-majority-direction', event: 'majority-direction', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'You have deliberated for more than eight hours, failed to reach unanimity and undertaken further discussion after my direction. I am satisfied it is appropriate to accept a majority verdict of eleven jurors agreeing. Continue first to seek unanimity. If that is not honestly possible, an eleven-to-one verdict may be returned. No smaller majority is lawful.', accessibleProposition: 'Only now, after the disclosed safeguards, may the court accept eleven-to-one; unanimity remains preferred.' }),
      cue({ id: 'sun-majority-limit', event: 'jury-discussion', speaker: 'Kessa Noor', tone: 'deliberation', text: 'This direction changes the number needed for a verdict, not the elements or anyone’s duty to decide honestly. It does not tell a lone juror to submit or the eleven to stop listening. If neither unanimity nor eleven-to-one forms, unable to agree remains a lawful result.', accessibleProposition: 'The majority direction changes only the numerical threshold and preserves independent judgment and a hung result.' }),
    ], 90, 'Confirm the numerical rule without treating it as pressure.'),
    scene('sun-final-ballot', 'The final ballot', 'deliberation', 'jury-room-ballot', [
      cue({ id: 'sun-final-review', event: 'jury-discussion', speaker: 'Foreperson Edda Rook', tone: 'deliberation', text: 'Before the final ballot, apply the path once more: murder first; manslaughter only if murder fails; Not Guilty if an element of both remains unproved; unable to agree if honest discussion cannot produce unanimity or eleven-to-one. Do not select the verdict you predict others will choose.', accessibleProposition: 'The final vote follows the ordered legal path and remains independent.' }),
      cue({ id: 'sun-final-ballot', event: 'final-ballot', speaker: 'Court officer', tone: 'formal', text: 'Seal your final position. The authored jurors now update gradually from the evidence-linked discussion; no random tie-break, forced conversion or seat-level disclosure occurs. The room may reach a unanimous verdict, a lawful eleven-to-one verdict, or report that it cannot agree.', accessibleProposition: 'The final deterministic ballot can yield unanimity, lawful majority or no agreement without coercion or randomness.' }),
    ], 140, 'Seal your final verdict from the legal elements and admitted evidence.', 'final-vote', ['Murder', 'Manslaughter', 'Not Guilty', 'Unable to agree']),
    scene('sun-verdict', 'Return to open court', 'verdict', 'courtroom-verdict', [
      cue({ id: 'sun-verdict-return', event: 'verdict-return', speaker: 'Clerk', tone: 'formal', text: 'The jury returns. The accused stands. The clerk asks the foreperson whether the jury is unanimous, has reached an authorised majority, or cannot agree. Only then is the result selected by the completed deliberation spoken aloud in open court. No celebratory score, popularity count or editorial answer appears.', accessibleProposition: 'The accused stands and the jury’s actual result is formally returned before any analysis or tally.' }),
      cue({ id: 'sun-verdict-confirm', event: 'verdict-return', speaker: 'Judge Sel Aven', tone: 'ruling', text: 'The court records the verdict exactly as returned. If it is a majority verdict, the foreperson confirms only that the lawful numerical threshold was met, not who dissented. If the jury cannot agree, I discharge it without criticism. Jurors are not asked to explain or defend their votes in open court.', accessibleProposition: 'The court records the result without exposing juror identities or criticising a hung jury.' }),
    ], 95, 'Hear the open-court return before opening any analysis.'),
    scene('sun-analysis', 'Two lawful readings', 'analysis', 'courtroom-empty', [
      cue({ id: 'sun-analysis', event: 'analysis', speaker: 'Judge’s neutral case note', tone: 'neutral', text: 'Analysis unlocks only now. It presents the strongest lawful route supporting the returned result and the strongest lawful counter-analysis from the same admitted record. It does not reveal a hidden correct answer. It identifies which element, inference or burden judgment separates the paths and preserves every exhibit limitation.', accessibleProposition: 'Post-verdict analysis presents balanced lawful reasoning and counter-reasoning without declaring correctness.' }),
      cue({ id: 'sun-analysis-close', event: 'analysis', speaker: 'Court officer', tone: 'formal', text: 'Your week is complete. The case remains available for catch-up and review, but your sealed first and final votes remain part of your private local record. Nothing is uploaded to a court, server, leaderboard or other player.', accessibleProposition: 'The completed case remains locally reviewable; private votes are not uploaded or compared.' }),
    ], 105, 'Compare both lawful paths without changing the verdict already returned.', 'reasoning', ['connect', 'distinguish', 'test-source', 'challenge-inference', 'raise-alternative', 'apply-burden']),
  ],
}

export const elevenMinutesSessions: CourtSession[] = [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
