import type { TrialRecord } from '../model/schema'

export const elevenMinutesTrialRecord: TrialRecord = {
  jurisdiction: 'State of Orinth',
  court: 'Superior Criminal Court of Aster Reach',
  charge: 'Murder by intentional omission',
  accused: 'Mara Venn',
  deceased: 'Ilan Saye',
  plea: 'Not Guilty',
  offences: [
    {
      id: 'orinth-cc-s18', citation: 'Criminal Code s 18', title: 'Murder by act or omission',
      text: 'A person commits murder if, by a voluntary act or an intentional failure to perform a legal duty, that person causes death while intending to cause death or really serious injury.',
      elementQuestions: [
        'Did Mara Venn owe and intentionally fail to perform the legal duty identified under s 41?',
        'Did that intentional omission cause Ilan Saye’s death?',
        'At the time of the omission, did Mara Venn intend death or really serious injury?',
      ],
    },
    {
      id: 'orinth-cc-s22', citation: 'Criminal Code s 22', title: 'Manslaughter by criminal negligence',
      text: 'A person commits manslaughter if a deliberate act or omission breaches a legal duty and causes death, and the departure from reasonable care is so great, with so high a risk of death or serious injury, that it merits criminal punishment.',
      elementQuestions: [
        'If murder is not proved, did Mara Venn deliberately omit a step required by her duty?',
        'Did the omission cause death?',
        'Was the departure from reasonable care so great, and the risk so high, that it was criminal?',
      ],
    },
    {
      id: 'orinth-eca-s41', citation: 'Emergency Coordination Act s 41', title: 'Accepted distress alerts',
      text: 'A duty controller who accepts a credible distress alert must take reasonable dispatch steps unless reasonably prioritising a greater imminent peril.',
      elementQuestions: [
        'Did Mara Venn accept a credible distress alert?',
        'Were reasonable dispatch steps available?',
        'Was any delay a reasonable prioritisation of a greater imminent peril?',
      ],
    },
  ],
  agreedFacts: [
    'Mara Venn was the duty controller from 18:00 to 06:00 and was subject to Emergency Coordination Act s 41.',
    'Ilan Saye transmitted the recorded distress call from beacon AR-71 during the storm.',
    'The launch order for rescue craft Kestrel was withheld for eleven minutes after the incident was accepted.',
    'Ilan Saye died before rescuers reached the disabled survey vessel.',
    'The case and every person, institution and place in it are fictional.',
  ],
  evidence: [
    {
      id: 'ex-route', label: 'Harbour route diagram', kind: 'diagram',
      provenance: 'Prepared from the service chart by operations supervisor Nella Orr for this trial.',
      authentication: 'Orr identifies each marked station, beacon and rescue route from her operational duties.',
      integrity: 'Both parties agree the scale and positions are accurate; weather movement is not represented.',
      admittedThrough: 'Nella Orr', allowedUses: ['Understanding distance and the dispatch route'],
      limitations: ['Not proof of visibility, sea state or survival time'], replayable: true, status: 'admitted',
      accessibleProposition: 'The nearest rescue craft was based at North Station, eleven nautical miles from beacon AR-71.',
    },
    {
      id: 'ex-distress', label: 'Distress recording', kind: 'recording',
      provenance: 'Automatically recorded by the dispatch console during Ilan Saye’s call.',
      authentication: 'Dispatcher Peli Dorn recognises the console channel, voices and contemporaneous incident sequence.',
      integrity: 'Records custodian verifies the file hash against the write-once incident archive; the played copy is unedited.',
      admittedThrough: 'Peli Dorn and Tovan Mir', allowedUses: ['What the speakers said', 'Whether the alert was credible and recognised'],
      limitations: ['Audio quality may affect interpretation', 'May not be used to infer facts never spoken'], replayable: true, status: 'admitted',
      accessibleProposition: 'The caller identifies beacon AR-71; the controller repeats “AR-71” and says she has the position.',
    },
    {
      id: 'ex-launch-strip', label: 'Yellow launch strip', kind: 'document',
      provenance: 'Printed automatically when the distress incident was accepted, then recovered from Mara Venn’s console tray.',
      authentication: 'Tovan Mir matches its incident number and print sequence to the immutable system log.',
      integrity: 'The paper bears no alteration; the handwritten notation “hold—readiness” is not timestamped.',
      admittedThrough: 'Tovan Mir', allowedUses: ['The accepted beacon and the handwritten hold notation'],
      limitations: ['Handwriting alone does not prove when or why it was written'], replayable: true, status: 'admitted',
      accessibleProposition: 'The strip shows AR-71 and the handwritten words “hold—readiness”.',
    },
    {
      id: 'ex-audit-log', label: 'Incident audit log', kind: 'system-log',
      provenance: 'Generated automatically by the emergency coordination system.',
      authentication: 'Tovan Mir explains the account controls and identifies Mara Venn’s authenticated session.',
      integrity: 'The archive hash matches; the system clock was verified within two seconds that evening.',
      admittedThrough: 'Tovan Mir', allowedUses: ['Timing and identity of logged console actions'],
      limitations: ['The log records button actions, not the operator’s state of mind'], replayable: true, status: 'admitted',
      accessibleProposition: 'Venn’s account accepted AR-71, changed its priority, confirmed the change, and released Kestrel eleven minutes later.',
    },
    {
      id: 'ex-ready-display', label: 'Kestrel readiness display', kind: 'system-log',
      provenance: 'Snapshot retained with the incident log from North Station’s craft-status feed.',
      authentication: 'Rescue supervisor Jaro Pell explains the status feed and records custodian Mir links the snapshot to the incident.',
      integrity: 'The snapshot is complete, but the short label suppresses the separate maintenance-warning detail.',
      admittedThrough: 'Jaro Pell and Tovan Mir', allowedUses: ['What the controller could see about Kestrel’s displayed readiness'],
      limitations: ['READY meant crewed and launch-capable, not necessarily free from warnings'], replayable: true, status: 'admitted',
      accessibleProposition: 'Kestrel displayed READY throughout, while a separate page carried a steering-pressure warning.',
    },
    {
      id: 'ex-warning', label: 'Kestrel steering warning record', kind: 'document',
      provenance: 'Entered by Kestrel’s engineer during the pre-shift inspection.',
      authentication: 'Maintenance engineer Sera Quill identifies her entry and the warning code.',
      integrity: 'The entry predates the incident and was not changed after the event.',
      admittedThrough: 'Sera Quill', allowedUses: ['The warning known to the coordination system', 'Whether a cautious dispatch hold was plausible'],
      limitations: ['The warning did not itself prohibit launch'], replayable: true, status: 'admitted',
      accessibleProposition: 'A fluctuating steering-pressure warning required monitoring but did not prohibit launch.',
    },
    {
      id: 'ex-review', label: 'Pending certification review', kind: 'document',
      provenance: 'Draft review memorandum stored in the safety office before the storm.',
      authentication: 'Compliance director Oren Vale identifies the memorandum and its ordinary review path.',
      integrity: 'Metadata shows Ilan Saye authored the draft; it was not sent to Mara Venn.',
      admittedThrough: 'Oren Vale', allowedUses: ['Possible motive if the jury finds Venn knew its substance'],
      limitations: ['A draft is not a final finding', 'Its existence does not itself prove knowledge or intent'], replayable: true, status: 'admitted',
      accessibleProposition: 'The draft proposed suspending Venn’s controller certification, but the Crown must still prove she knew that.',
    },
    {
      id: 'ex-survival', label: 'Survival-window opinion', kind: 'expert-opinion',
      provenance: 'Opinion of marine survival physician Dr Eren Vos using accepted hypothermia and immersion data.',
      authentication: 'Vos states qualifications, sources, assumptions and the limits of individual prediction.',
      integrity: 'Both sides received the report and underlying tables; no calculation was withheld.',
      admittedThrough: 'Dr Eren Vos', allowedUses: ['Assessing whether earlier dispatch materially affected the chance of survival'],
      limitations: ['Cannot identify an exact time of death', 'Cannot say earlier dispatch certainly would have saved Saye'], replayable: true, status: 'admitted',
      accessibleProposition: 'An eleven-minute earlier dispatch would probably have brought rescue inside the medically significant window, but survival cannot be stated with certainty.',
    },
    {
      id: 'ex-competing', label: 'Concurrent incident board', kind: 'system-log',
      provenance: 'Automatic board export covering the controller’s full shift.',
      authentication: 'Peli Dorn and Tovan Mir identify the entries and timestamps.',
      integrity: 'The export is complete for the relevant hour and uses the verified system clock.',
      admittedThrough: 'Tovan Mir', allowedUses: ['Workload and competing peril at the time of the hold'],
      limitations: ['A listed incident is not necessarily a greater imminent peril'], replayable: true, status: 'admitted',
      accessibleProposition: 'Four incidents were open; only one involved people already in the water, and another craft was assigned to it.',
    },
    {
      id: 'struck-rumour', label: 'Struck workplace rumour', kind: 'oral-testimony',
      provenance: 'An unresponsive phrase volunteered by Oren Vale.',
      authentication: 'Not authenticated.', integrity: 'Not tested and not admitted.', admittedThrough: 'No witness',
      allowedUses: ['None'], limitations: ['Must be entirely disregarded'], replayable: false, status: 'struck',
      accessibleProposition: 'This material is legally absent and must not be used for any purpose.',
    },
  ],
  witnesses: [
    { id: 'w-orr', name: 'Nella Orr', calledBy: 'Crown', role: 'Operations supervisor', chiefCueIds: ['mon-orr-chief-1', 'mon-orr-chief-2'], crossCueIds: ['mon-orr-cross-1', 'mon-orr-cross-2'], reexaminationCueIds: [], reexaminationScope: [] },
    { id: 'w-dorn', name: 'Peli Dorn', calledBy: 'Crown', role: 'Junior dispatcher', chiefCueIds: ['tue-dorn-chief-1', 'tue-dorn-chief-2'], crossCueIds: ['tue-dorn-cross-1', 'tue-dorn-cross-2'], reexaminationCueIds: ['tue-dorn-re-1'], reexaminationScope: ['Whether the competing rescue already had a craft assigned'] },
    { id: 'w-mir', name: 'Tovan Mir', calledBy: 'Crown', role: 'Records custodian', chiefCueIds: ['tue-mir-chief-1', 'tue-mir-chief-2'], crossCueIds: ['tue-mir-cross-1'], reexaminationCueIds: [], reexaminationScope: [] },
    { id: 'w-pell', name: 'Jaro Pell', calledBy: 'Crown', role: 'Rescue supervisor', chiefCueIds: ['wed-pell-chief-1'], crossCueIds: ['wed-pell-cross-1'], reexaminationCueIds: ['wed-pell-re-1'], reexaminationScope: ['What READY conveyed despite the separate warning'] },
    { id: 'w-vos', name: 'Dr Eren Vos', calledBy: 'Crown', role: 'Marine survival physician', chiefCueIds: ['wed-vos-chief-1'], crossCueIds: ['wed-vos-cross-1'], reexaminationCueIds: ['wed-vos-re-1'], reexaminationScope: ['Difference between certainty and a medically significant probability'] },
    { id: 'w-vale', name: 'Oren Vale', calledBy: 'Crown', role: 'Compliance director', chiefCueIds: ['wed-vale-chief-1'], crossCueIds: ['wed-vale-cross-1'], reexaminationCueIds: [], reexaminationScope: [] },
    { id: 'w-rusk', name: 'Tali Rusk', calledBy: 'Defence', role: 'Human-factors specialist', chiefCueIds: ['thu-rusk-chief-1', 'thu-rusk-chief-2'], crossCueIds: ['thu-rusk-cross-1'], reexaminationCueIds: ['thu-rusk-re-1'], reexaminationScope: ['Whether an explanation of error is the same as an opinion about intent'] },
    { id: 'w-quill', name: 'Sera Quill', calledBy: 'Defence', role: 'Maintenance engineer', chiefCueIds: ['thu-quill-chief-1'], crossCueIds: ['thu-quill-cross-1'], reexaminationCueIds: ['thu-quill-re-1'], reexaminationScope: ['Whether launch authority remained with the duty controller'] },
  ],
  objections: [
    { id: 'obj-1', cueId: 'tue-def-objection', madeBy: 'Defence', ground: 'hearsay', timing: 'pre-answer', ruling: 'sustained' },
    { id: 'obj-2', cueId: 'wed-def-objection', madeBy: 'Defence', ground: 'relevance', timing: 'pre-answer', ruling: 'overruled' },
    { id: 'obj-3', cueId: 'wed-postanswer-ruling', madeBy: 'Defence', ground: 'hearsay', timing: 'post-answer', ruling: 'sustained', struckEvidenceId: 'struck-rumour' },
    { id: 'obj-4', cueId: 'thu-crown-objection', madeBy: 'Crown', ground: 'argumentative', timing: 'pre-answer', ruling: 'sustained' },
  ],
  accusedTestifies: false,
}
